version: "3.9"
services:
    wordpress:
      container_name: wordpress
      image: wordpress:php8.1-apache
      restart: always
      stdin_open: true
      ports:
        - 3333:80 
      tty: true
      environment:
          WORDPRESS_DB_HOST: mariadb
          WORDPRESS_DB_USER: db_user
          WORDPRESS_DB_PASSWORD: db_user_pass
          WORDPRESS_DB_NAME: db_name
      volumes:
          - ./wordpress:/var/www/html 
    mariadb:
      container_name: mariadb
      image: mariadb
      restart: always
      environment:
          MYSQL_DATABASE: db_name
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_user_pass
          MYSQL_RANDOM_ROOT_PASSWORD: 'root_pass'
      volumes:
          - ./mariadb:/var/lib/mysql
